version: "3.8"

services:
    web:
        container_name: signup_api
        restart: "on-failure"
        build: ./
        command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --reload
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
