version: '3.7'

services:

    db:
        image: postgres:14-alpine
        env_file:
            - ./backend/.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432:5432
        networks:
            - web

    backend:
        restart: on-failure
        env_file:
            - ./backend/.env
        build:
            context: ./backend
            dockerfile: backend.dockerfile
            args:
                INSTALL_DEV: 'false'
        command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --reload
        volumes:
            - ./:/usr/src/app/
        depends_on:
            - db
        ports:
            - 8000:8000
        networks:
            - web

    nginx:
        restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/fast-api.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web

networks:
    web:
        driver: bridge

volumes:
    postgres_data:
