[tool.poetry]
name = "signup_api"
version = "0.1.2"
description = "An asynchronous Fast API service for signups and Telegram integration"
authors = ["mbrav <mbrav@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "*"
fastapi-pagination = {extras = ["sqlalchemy"], version = "*"}
pydantic = {extras = ["email", "dotenv"], version = "*"}
uvicorn = "*"
SQLAlchemy = "*"
PyMySQL = "*"
python-jose = {extras = ["cryptography"], version = "*"}
passlib = {extras = ["argon2"], version = "*"}
python-multipart = "*"


[tool.poetry.dev-dependencies]
pytest = "*"
pytest-env = "*"
flake8 = "*"
autopep8 = "*"
requests = "*"

[tool.pytest.ini_options]
minversion = "6.2"
testpaths = [
    "tests/",
]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
]
addopts = "-vv -p no:cacheprovider"
env = ["TESTING=True"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
